/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.xkerman;

import com.gargoylesoftware.htmlunit.WebClient;
import com.gargoylesoftware.htmlunit.html.HtmlPage;

public class App {
    public static void main(String[] args) throws Exception {
        if (args.length < 1) {
            return;
        }
        String url = args[0];
        System.out.println("loading: " + url);
        WebClient client = new WebClient();
        HtmlPage page = client.getPage(url);
        client.waitForBackgroundJavaScript(10 * 1000);
    }
}
